dist: xenial
sudo: true
language: python
python:
    - "3.7"
install: 
    - pip install -r requirements.txt
    - pip install qgrid --upgrade --pre
    - pip install -U git+https://github.com/ozgur/python-linkedin --no-deps
    - export PYTHONPATH=src
script:
    - python setup.py unittests
