dist: trusty
language: python
python:
    - "3.6"
install: 
    - pip install -r requirements.txt
    - pip install qgrid --upgrade --pre
    - pip install -U git+https://github.com/ozgur/python-linkedin --no-deps
script:
    - python setup.py unittests
